apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-server-crb
subjects:
- kind: ServiceAccount
  name: ocs-provider-server
  namespace: openshift-storage
roleRef:
  kind: ClusterRole
  name: provider-server-cr
  apiGroup: rbac.authorization.k8s.io
